### ISSUE TITLE
Add init command

### ISSUE THREAD

**Issue by dustinleblanc** [kalabox/lando#110]
As a Lando User,
I want to be able to generate my lando config file using the app cli,
So that I can quickly bootstrap Lando on new projects or add it existing ones.

Looking up the recipes and manually creating the files is totally fine for now, but I imagine being able to quickly generate a Lando config for a project will be a valuable feature for both new and seasoned users.

This could start as generating a commented stub file with a default assumed recipe, and eventually grow into a question/answer setup (not needed at first I'd think).

**Comment by pirog** [comment]
@dustinleblanc this is **DEFINITELY** in the immediate roadmap!
