### ISSUE TITLE
Terminus flops on --help, repeating same command suggestion

### ISSUE THREAD

**Issue by seanr** [kalabox/lando#131]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

*v3.0.0-alpha.8*

Have you previously installed lando? If so, what version?

*Yes, 3.0.0-alpha.6, but did a full uninstall and a fresh install yesterday.*

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

*Terminus seems not to recognize valid commands when accessed via lando.*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example:

```
seanr@Seans-MacBook-Pro ~/Sites/publisher2 (master) $ lando terminus --help
/usr/local/bin/lando /snapshot/cli/bin/lando.js terminus

Options:
  --help, -h  Show help                                                [boolean]
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

*Possibly, but appears to be  bug after discussing with @pirog.*

Does this bug prevent you from using lando?

*It prevents integration with Pantheon, but not local development.*

Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

*I need to be able to set up integration with Pantheon. One part of that process is Terminus, which does not appear to be working correctly at present.*

Please provide some detail on how lando can help solve this problem

*Verify that all Terminus commands run correctly via `lando terminus ...`.*

**Comment by pirog** [comment]
@seanr this should be in the latest dev release and will roll out with the beta
