### ISSUE TITLE
set PHP 7.0 as default for Pantheon 

### ISSUE THREAD

**Issue by shaal** [kalabox/lando#132]
I'm following the directions on https://docs.lndo.io/tutorials/pantheon-working.html, to get a pantheon site on my local ubuntu.
It's downloading the code, but when i run `lando start`, i receive this error message -
```
Pulling appserver (kalabox/pantheon-php:7.1-fpm)...
ERROR: manifest for kalabox/pantheon-php:7.1-fpm not found
```
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/lando/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/lando/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?
Ubuntu 16.10 64bit
*Example: v3.0.0-alpha1 on Windows 10 Professional*

Have you previously installed lando? If so, what version?
Yes, I've installed lando v3.0.0-alpha13
*Example: Yes, I've installed lando v3.0.0-alpha4*

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

*Example: I tried to create a pantheon site but got a `LowerCase` not defined exception*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example:

> 1. Started up GUI
> 2. Clicked on my Pantheon account in the sidebar
> 3. Selected a site and an environment
> 4. Kept the default create options and pressed submit

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Does this bug prevent you from using lando?
yes

Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

*Example: As a lando user who works with Drupal sites that have large databases, I want the option to exclude unnecessary database tables from being pulled when I update my site because I want faster "site pull" actions.*

Please provide some detail on how lando can help solve this problem

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Comment by seanr** [comment]
Docs are a little inconsistent, but this worked for me:

https://docs.lndo.io/recipes/pantheon.html

**Comment by seanr** [comment]
Note the pantheon.yml in that example.

**Comment by pirog** [comment]
@seanr interested in what you think is inconsistent. `pantheon.yml` is not a requirement.

I think this might just be a downstream bug that sets the wrong php version when there is no pantheon.yml. @shaal i'd be interested to see your `.lando.yml` file here to help replicate.

**Comment by pirog** [comment]
@shaal can def confirm this is an issue if you use the pantheon recipe with either `drupal8` or `wordpress` as the framework and you *DO NOT* have a `pantheon.yml`

**Comment by pirog** [comment]
@shaal this is fixed in the latest dev release

**Comment by shaal** [comment]
I was able to test it on this version - v3.0.0-alpha.13
When a new version comes out - I would love to test it again.

**Comment by pirog** [comment]
@shaal we roll development builds after every commit over here:
https://docs.lndo.io/installation/installing.html#development-builds

so you should be able to test against that if you dont want to wait for the official release
