### ISSUE TITLE
Pantheon recipe filemount may not exist

### ISSUE THREAD

**Issue by dsquaredb** [kalabox/lando#133]
**Tell us about your setup**

What is your lando version and operating system?
v3.0.0-alpha.13
macOS 10.12.5

Have you previously installed lando? If so, what version?
Yes, not sure of version.

**Tell us about your bug**
Files not imported on first 4 tries, but finally successful on 5th try.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Pulled down a D8 site from Pantheon
2. Used terminus to make a copy of the Pantheon dev database and import it
3. Checked local site and saw it was working, but just missing files
4. Used terminus to make a copy of Pantheon dev files
5. Tried to add the files using this terminus command: 
`lando ssh -c "tar -xzvf /tmp/files.tar.gz -C \$LANDO_MOUNT/\$FILEMOUNT --strip-components 1"`

6. Got the following error message: 
`tar: /app/sites/default/files: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now`

7. Attempted to run the terminus command three more times with same error
8. Went to add the Files folder and it was already there, so ran the command again and this time it added the files 
9. Checked the local site and everything looked correct and works as designed

**Comment by pirog** [comment]
Note to self: it might be good to just include this in our helper import scripts for db and files
