### ISSUE TITLE
Lando doesn't allow build with non-existent id/site/env values for Pantheon recipe

### ISSUE THREAD

**Issue by seanr** [kalabox/lando#134]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

*v3.0.0-alpha8 on OSX 10.12.5*

**Tell us about your bug**

Mising id/site/env values in .lando.yml cause the following error when running `lando start`:

```
lando start
error:  YAMLException: unacceptable kind of an object to dump [object Undefined]
```

**Tell us more**

Values can be empty, but the keys have to be preset for successful build.

**Comment by pirog** [comment]
@seanr i *think* this should be fixed in alpha.13
