### ISSUE TITLE
Refactor/reorg docs

### ISSUE THREAD

**Issue by pirog** [kalabox/lando#139]
Let's do a pass on the docs so we can update appropriate sections with the new `lando init` command. Particularly we should look at...

* Getting Started Section
* Add a table of contents to help people pick/choose starting point
  * Starting w/existing codebase
  * Pulling codebase from Github
  * Pulling codebase from Pantheon

These rely upon the creation of other docs that we don't have yet:

* Configuring lando.yml
  * Using init command
  * Manually creating lando.yml
  * Links to configuration docs
* Configuring...
  * Recipes
  * Tooling
  * Services
* Advanced Topics/Follow-up
  * Relevant tutorials
  * Add helpful tutorials to README/index.html

**Comment by reynoldsalec** [comment]
Meta docs organization:

1. Getting Started
2. Tutorials
3. Advanced Config

**Comment by pirog** [comment]
1. Getting my codebase and getting my lando file(lando init with methods)
2. Starting my site (emphasize that we do not pull files and database)
3. Importing my data
  3. Pulling files and data
  4. Manually files and data import
5. Tooling?
6. Config
  7. (envvars/
  8. pantheon.yml)
7. Advanced (redis/solr/varnish && lando info)
  8. multidev?
8. Other helpful tutorials
  9. build steps (composer)
  10. front end
