### ISSUE TITLE
Write a composer tutorial

### ISSUE THREAD

**Issue by pirog** [kalabox/lando#146]
Let's write a tutorial (https://github.com/kalabox/lando/tree/master/docs/tutorials) that a user can follow so that when they are done reading they have a good idea of how to set up and use composer things with lando. presumably this would include

1. adding in a composer install build step
2. adding tooling to composer tools like phpunit/phpcs
3. adding composer test (scripts session in composer.json, simple linting/code standards example)

**Comment by serundeputy** [comment]
PR: https://github.com/kalabox/lando/pull/230
