### ISSUE TITLE
Write a tutorial on how to run lando in a CI envrionment

### ISSUE THREAD

**Issue by pirog** [kalabox/lando#147]
Let's write a tutorial (https://github.com/kalabox/lando/tree/master/docs/tutorials) that a user can follow so that when they are done reading they have a good idea of how to set up lando in travis or circle ci so they can super streamline their devops. presumably this would include

1. installing kalabox on travis/circle
2. running a lando start comand
3. having lando handle dependency installation 
4. having lando handle task running

(a basic code linting and code standards check here is probably best)

**Comment by serundeputy** [comment]
PR: https://github.com/kalabox/lando/pull/246

**Comment by serundeputy** [comment]
@pirog updated with `examples/lando-and-ci/.lando.yml` full example file and included in the bottom of the tutorial.
