### ISSUE TITLE
init mysite pantheon waits for a password

### ISSUE THREAD

**Issue by KenWatts** [kalabox/lando#153]
Bug Report
==========

lando v3.3.3-alph.13 on Windows 10 Professional

First install - But I do have Kalabox installed.

When I attempted to run lando init mysite pantheon the process went smoothly until lando displayed the randomart image, then appeared to hang.  When I destroyed the app and ran init again, this time with a -vvv flag, it became clear that it was waiting for a password.  (Without the debug flag there was no indication of this)

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example:

> 1. lando init mysite pantheon
> 2. select account
> 3. Selected a site and an environment
> 4. select an installation directory
> 5. lando creates keys then waits for a password without any prompt

Could better documentation have prevented this issue? if so what should we change?

I would guess making the prompt for the password show up could be counted as documentation, though it would be within the script itself. But the real fix would be to keep it from needing the password.

Does this bug prevent you from using lando?

It would have if pirog hadn't suggested the debug flag.

**Comment by pirog** [comment]
@KenWatts i think this might be caused by the deadly #181
