### ISSUE TITLE
Add elastic search service

### ISSUE THREAD

**Issue by pirog** [kalabox/lando#16]

**Comment by reynoldsalec** [comment]
Ok, got the elasticsearch service up and running and creating a basic express app as an example, but for some reason can't connect to `search:9999` service as specified in the express app. Can connect to the elasticsearch instance just fine externally from `hostname:9999`.

Once I've figured that out, should figure out passing more config variables to elasticsearch from .lando.yml and we'll have a full-fledged elasticsearch service!

**Comment by pirog** [comment]
@reynoldsalec sounds good!
