### ISSUE TITLE
MailHog subdomain.  Not working with proxy server.

### ISSUE THREAD

**Issue by serundeputy** [kalabox/lando#167]
In #64 adding a MailHog service we want to provide users with a nice subdomain of their app, but behind a proxy the MailHog container converts the request from http to a websocket (`ws`) and it has no idea what this subdomain is.

So, we need to figure out how to get the MailHog container recognize and be able to resolve these subdomains.

**Comment by pirog** [comment]
@serundeputy i think this should be resolved by #169

**Comment by pirog** [comment]
@serundeputy using `traefik` seems to do the trick although we need to improve its stability first
