### ISSUE TITLE
user 33 doesnt exist and other linux perm issuez

### ISSUE THREAD

**Issue by pirog** [kalabox/lando#184]
Seems to happen rarely in Linux, i think this is a race condition where we might just want to delay a reasonable amount of time until the user mapping is sorted out

additionally we should bump up things like `/usr/local/bin` that need correct permissions sooner.

**Comment by cferdinandi** [comment]
Is there some sort of magical fix for this? Ran a fresh install today, running into this issue, and cannot make it go away.
