### ISSUE TITLE
Ability to rebuild specific service

### ISSUE THREAD

**Issue by seanr** [kalabox/lando#223]
I'm running v3.0.0-alpha.17 on OSX. When I rebuild my app (Drupal 8 using the Pantheon recipe), the database does not persist. Ideally, I'd like a way to specify which services I want to rebuild, or perhaps (via config) to specify services that should persist when rebuilding the application (i.e. a sort of lock).

**Comment by pirog** [comment]
@seanr i've tried this out on a few `pantheon` sites and the db seems to persist on a rebuild. Can you post up the command you are running to do the rebuild? Can you also open a new issue that is specifically about the non-persistent rebuild you are experiencing?

+1 on rebuilding specific services though. going to go ahead with that.
