### ISSUE TITLE
Windows installation completes but won't start

### ISSUE THREAD

**Issue by brentratliff** [kalabox/lando#229]
Bug Report
==========

Windows 10 Pro w/HyperV (Creator's Update)

Lando 3.0.0-alpha18 

Have you previously installed lando? No

**Tell us about your bug**

1. Closed all programs (including Docker) and ran the installer
2. Restarted Computer after successful installation
3. Double clicked shortcut and got "Windows is searching for lando.exe"
4. Checked the path of the shortcut and it points to 'gui'
5. 'gui' does not exist in the C:/Program Files/Lando directory

**Tell us more**

I ran the installer twice including once as administrator explicitly with the same result.  The installer powered up Docker and looked to finish but it may be an incomplete package.

Does this bug prevent you from using lando? Yes

**Comment by pirog** [comment]
@brentratliff there is no GUI in lando at this time, we should remove the shortcut link until we do

**Comment by brentratliff** [comment]
Well then, that make sense.  I will follow the setup instructions for the command line Pantheon Drupal containers.  Is there a way to connect to the webserver via WSL Bash on Windows?  I control composer and drush through that so I'm hoping it will work. Thanks.

**Comment by pirog** [comment]
Will keep this open so we can remove the shortcut.

Not sure about WSL Bash but i'd go through the Lando docs. Depending on the project you are spinning up Lando will provide tools like Drush and Composer for you to use and its recommend you use those instead of whatever you've installed locally.
