### ISSUE TITLE
Drush commands result in File Not Found error

### ISSUE THREAD

**Issue by sysadminbeach** [kalabox/lando#234]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/lando/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/lando/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? 

v3.0.0-alpha.18 Windows 10 Professional Build 1703

Have you previously installed lando? If so, what version?

no

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

After pulling down a Pantheon site that was installed via composer/drops8 drush commands do not work. Drush commands result in a file or directory not found. If you access the appserver container directly via SSH drush commands in /app yield the same result, however if you leave /app for any other directory then it will work fine so long as /app is not in that path. 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example:

> 1. lando init mysite pantheon
> 2. lando start
> 3. cd web
> 4. lando drush status

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Does this bug prevent you from using lando?
Yes, using drush is pretty necessary.

**Comment by pirog** [comment]
@sysadminbeach im guessing this is probably some sort of bug or unhandled situation in the drops8 composer repo since lando itself doesnt really do anything special as far as drush is concerned. 

are you using https://github.com/pantheon-systems/example-drops-8-composer?

**Comment by sysadminbeach** [comment]
That is the one I am using.

**Comment by pirog** [comment]
@sysadminbeach awesome! i'll try to replicate sometime soon.

**Comment by pirog** [comment]
@sysadminbeach not able to replicate this (im trying on macOS although i dont *think* that should matter) here are the steps i took

```bash
# Spin up drops8 composer project
composer create-project pantheon-systems/example-drops-8-composer d8composer
cd d8composer
composer prepare-for-pantheon

# Copy below .lando.yml into root directory
# Note: using this just to get a pantheon env spun up without having to `lando init` 
# and connect to a pantehon upstream

# Do the lando
lando start
cd web
lando drush status
```

```yml
name: d8composer
recipe: pantheon
config:
  framework: drupal8
```

**Comment by sysadminbeach** [comment]
Thanks for checking, did you finish the rest of the steps for standing up an example-drops-8 site on pantehon, which involves committing that code over the original pantheon repo and finishing the drupal install via browser?

**Comment by pirog** [comment]
i did not but because that seems decidedly outside of lando concerns. if you commit the code to pantheon correctly you are effectively running the example i posted above.

**Comment by sysadminbeach** [comment]
found it. It seems my images did need to be deleted since the beta 8 release and drush started working. I must have had an older version that cause the issue. Thank you for the feedback and verifying it wasn't lando!

**Comment by cgrill** [comment]
@ghost, can you describe a little more about your solution? What are the images you deleted? I'm seeing a similar issue in lando alpha 25. 

If I do this:
lando init mysite pantheon
lando start
cd web
lando drush status

I get this:
/app/vendor/bin/drush.launcher: 1: /app/vendor/bin/drush.launcher: ../drush/drush/drush.launcher: not found

thanks!

**Comment by cgrill** [comment]
Thanks for the input. sorry, yes beta25

drush.launcher is in the vendor folder as expected, though the /vendor/ is not in an /app/ folder. I tried copying all the drush files into a new /app/ folder but no luck. This is a pantheon recipe - not sure if that plays into it. All the other CLI tools work fine. I can create a separate issue if needed. It seemed pretty close to this one but no luck yet.

**Comment by pirog** [comment]
@cgrill if you don't have `vendor` inside of `/app` then that is your issue. There are various reasons why this could be happening from missing a build step to the Docker file daemon crashing.
