### ISSUE TITLE
MariaDB example is not working.

### ISSUE THREAD

**Issue by serundeputy** [kalabox/lando#24]
* `cd LANDO/examples/mariadb`
* `lando start`

output:

```
geoff@yep mariadb (master) $ lando start
(node:26794) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: TypeError: this.isRunning is not a function
(node:26794) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by serundeputy** [comment]
I think this was because I did not have a mariadb docker image.  I was issuing the command `lando start`.

After doing `lando rebuild -vvvv` it pulls in the images and can start the mariadb example.

**Comment by pirog** [comment]
Hmmm it SHOULD auto pull the image if you don't have it.  This seems to
happen for me.
