### ISSUE TITLE
Error following instructions for existing drupal 7 site

### ISSUE THREAD

**Issue by jsibley2** [kalabox/lando#291]
Following the documentation, I cd'd into my site directory on my local pc (running Windows10 Professional). Then I tried:

lando init --recipe drupal7

I received this error message:

Not enough non-option arguments: got 0, need at least 1

This is probably a stupid error on my part, but maybe I won't be the only one to do whatever I did. Is there an argument that I'm missing? If so, which argument?

Thanks.

**Comment by pirog** [comment]
@jsibley2 what version are you running?
Please see: https://docs.lndo.io/changelog/2017.html#v300-beta10---august-19-2017

**Comment by jsibley2** [comment]
Yes, I was a couple of versions behind. Thanks!
