### ISSUE TITLE
D8 Pantheon recipe app in infinite loop checking URLs on start up.

### ISSUE THREAD

**Issue by serundeputy** [kalabox/lando#300]
Lando
------
commit: `cdaeb93`

version:
```bash
geoff@yep docs (master) $ lando.dev version
v3.0.0-beta.10
```

I have a D8 Pantheon app.  On `lando start` it gets into an infinite loop checking the `localhost` URLs.  It quickly gets passed checking the `lndo.site` URLs and then gets stuck on the `localhost` URLs.

`lando start -- -v`:
At first you can see the `*.lndo.site` URLs
```bash
info: Checking to see if https://localhost:32771 is ready.
info: Checking to see if http://localhost:32772 is ready.
info: Checking to see if https://localhost:32775 is ready.
info: Checking to see if http://localhost:32774 is ready.
info: Checking to see if http://lightupthemap.lndo.site is ready.
info: Checking to see if https://lightupthemap.lndo.site is ready.
info: Checking to see if https://localhost:32775 is ready.
info: Checking to see if http://localhost:32774 is ready.
info: Checking to see if http://lightupthemap.lndo.site is ready.
info: Checking to see if https://lightupthemap.lndo.site is ready.
```

After a few seconds you see only `localhost` URLs:

```bash
info: Checking to see if http://localhost:32772 is ready.
info: Checking to see if http://localhost:32774 is ready.
info: Checking to see if https://localhost:32775 is ready.
info: Checking to see if http://localhost:32772 is ready.
info: Checking to see if https://localhost:32775 is ready.
info: Checking to see if http://localhost:32772 is ready.
info: Checking to see if http://localhost:32774 is ready.
info: Checking to see if https://localhost:32775 is ready.
info: Checking to see if http://localhost:32772 is ready.
info: Checking to see if http://localhost:32774 is ready.
info: Checking to see if https://localhost:32775 is ready.
info: Checking to see if http://localhost:32772 is ready.
info: Checking to see if http://localhost:32774 is ready.
info: Checking to see if https://localhost:32775 is ready.
info: Checking to see if http://localhost:32772 is ready.
```

And it will continue checking those indefinitely (it does not time out after some finite number of retries).

At this point if you `Ctrl+c` the `lando start` command the app is started up correctly and you can access it via the `lndo.site` URLs and use the app just fine both through the browser and lando interactions like `lando drush` or `lando mysql` for example.

I've not been able to determine if this an app level problem or lando issue, but this is what I know about it.

**Comment by serundeputy** [comment]
Here is `lando start -- -vvv`:

```bash
info: Checking to see if https://lightupthemap.lndo.site is ready.
info: Checking to see if http://localhost:32781 is ready.
verbose: https://lightupthemap.lndo.site is now ready.
verbose: http://lightupthemap.lndo.site is now ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32782 is ready.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if http://localhost:32782 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if http://localhost:32782 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if http://localhost:32782 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if http://localhost:32782 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
info: Checking to see if http://localhost:32781 is ready.
info: Checking to see if http://localhost:32782 is ready.
info: Checking to see if https://localhost:32783 is ready.
debug: https://localhost:32783 not yet ready with code 400.
```

Which reveals that the localhost URLs are 400.

**Comment by pirog** [comment]
@serundeputy is do you know which services those localhost addresses match up with? you can run `lando info` and cross reference the urls that way. 

i recently had a similar issue when enforcing `HTTPS` for a Pantheon app: #311

**Comment by ptmkenny** [comment]
Had this same issue when running `lando start`; the cause was forcing SSL in settings.php, same as #311

**Comment by pirog** [comment]
@ptmkenny good to know, i wonder if we could somehow force Lando's URL check to not follow redirects. I think that would resolve this.

**Comment by pirog** [comment]
Pushing up a hotfix release for this!

**Comment by rafalfaro-hangar** [comment]
Hi in my case the problem was that the older versions of lando didn't strip the dashes in the name of the app to create the url, so Drupal would cause an error when trying to access the site that had the trusted_host_patterns setting enabled and of course the url wouldn't match the new url without dashes. This error caused by Drupal was causing lando to highlight the url with color red. I leave this here in case someone has the same issue.

**Comment by aimhighagency** [comment]
Try restarting Docker
I was having a similar issue. (lando start was hanging when Checking the localhost on the edge_ssl port)
Tried a few of the options above but nothing worked. 
I tried restarting Docker and BAM! Started working again. 

Hope this helps someone!

**Comment by RichardDavies** [comment]
@aimhighagency 	I've encountered a similar issue (https://github.com/lando/lando/issues/1538) and found that restarting Docker _sometimes_ temporarily resolves it too (until you need to do another lando start/restart...) 

I sure wish I could figure out what the root cause was and find a more permanent solution. But so far, I haven't been able to find anything in my logs indicating a problem with anything. It just seems to hang while checking to see if the service URLs are ready.
