### ISSUE TITLE
the input device in not a TTY - Need to clarify win terminal usage in the docs

### ISSUE THREAD

**Issue by brentratliff** [kalabox/lando#301]
Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Please review the [current list of issues](https://github.com/kalabox/lando/issues) to make sure you are not submitting a duplicate.
2.  Please tag your issue appropriately. Please review the [tagging criteria](https://docs.lndo.io/dev/contributing.html).
3.  Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

*v3.0.0-beta10 on Windows 10 Professional*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```name: usna-97
recipe: drupal7
config:
  webroot: .
```

**Tell us about the command you were running**

```bash
lando start
lando db-import database.sql.gz

```

**Tell us about the error you got**
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

When I initally created the lando site I got the same error at lando start but it worked the second time.  The 'lando db-import' gives the error every time.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
1. lando init --recipe drupal7
2. lando start
3. lando db-import database.sql.gz
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Does this bug prevent you from using lando?
Yes

**Comment by brentratliff** [comment]
I also tried doing a lando init pantheon.  It found my sites but when creating the app, it failed with the same error.

**Comment by pirog** [comment]
@brentratliff i think on Windows you need to be using either CMD/POWERSHELL as your shell. NodeJS (which is the underlying tech powering lando) doesn't play well with "pseudo" shells eg anything cygwin based. 

This is not made super clear in the documentation and it should be

**Comment by brentratliff** [comment]
Yes, that was it.  I assumed I was supposed to use git bash since it shipped with it and added 'lando' to the git bash $path.

**Comment by pirog** [comment]
@brentratliff im going to alter this issue so we can at least update the docs around this requirement

**Comment by pirog** [comment]
@brentratliff i've added this to the docs
