### ISSUE TITLE
Pantheon recipe hangs on [notice] Logging in via machine token

### ISSUE THREAD

**Issue by brentratliff** [kalabox/lando#302]
Please complete the following steps.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

v3.0.0-beta10 on Windows 10 Professional
v3.0.0-beta10 on MacOS Sierra

**Tell us about your `.lando.yml`**

```name: usna97-v2
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: usna97-v2
  id: 
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

api_version: 1

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando init pantheon
lando start
```

**Tell us about the error you got*

```bash
[notice] Logging in via machine token
```

**Tell us generally about your bug**

I got the exact same error on Windows 10 and MacOS Sierra on the same Pantheon site.  It hangs at logging in.

*Example:*

```bash
1.lando init pantheon
2. chose site
3. site built successfully and pulled down the codebase via git
4. hangs on lando start
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Does this bug prevent you from using lando?
Yes

**Comment by pirog** [comment]
@brentratliff if its hanging at logging you in  you might want to check with the pantheon folks, i know they've had issues with their API lately. 

how long is it hanging for? what kind of site are you starting?

**Comment by brentratliff** [comment]
I figured it was a Pantheon issue.  I used the drupal7 recipe and manually imported my Pantheon site. That's working fine except for the tmp files directory and the ability to write to the sites/default/files directory on Windows.  I'll keep troubleshooting.

**Comment by ptmkenny** [comment]
I'm seeing the same issue.

I'm on Windows 10 Pro with lando beta 13.  I have a Pantheon D8 site that is run through Github using the instructions here: https://pantheon.io/docs/guides/github-pull-requests/

From the cloned repo on my machine, I ran:

```
lando init --recipe pantheon
lando start
```

But I also got a hang on `[notice] Logging in via machine token`.  I let it run about 30 minutes before I gave up.

So I then ran

```
lando destroy
lando init --recipe pantheon
lando terminus auth:login --machine-token=MYSECRET
lando start
```

This also hung at `[notice] Logging in via machine token`.

**Comment by pirog** [comment]
@brentratliff @ptmkenny i'd recommend you run `lando start -- -vvv` so you can see where exactly this is getting hung up. There are a few known issues (such as #311) where you can get `lando start` to hang for a pantheon app but it depends on app level configuration (read: out of our direct control).

**Comment by ptmkenny** [comment]
Thanks, that was it-- same issue as #300

**Comment by pirog** [comment]
Pushing up a hotfix release for this!
