### ISSUE TITLE
Pantheon recipe- can pull db but not files

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/lando#329]
Bug Report
==========

What is your lando version and operating system?

v3.0.0-beta13 on Windows 10 Professional

**Tell us about your `.lando.yml`**

name: mysite
recipe: pantheon
config:
framework: drupal8
env: dev
site: mysite
id: something-something
webroot: web/

**Tell us about the command you were running**

```
lando init --recipe pantheon
lando start
lando pull

```

**Tell us about the error you got**

When I run the command to pull, I choose the 'dev' db and 'dev' files.

The db pull completes successfully.

However, the file pull fails with this error:

```
Checking for /user/.lando/keys/pantheon.lando.id_rsa
Pulling files...
ssh: Could not resolve hostname appserver.initialmodulepack.somenumberssomenumbers.drush.in: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.1]

Pull complete!
```

I think the problem here is that the hostname being used is appserver.initialmodulepack-- "initialmodulepack" is my local git branch (currently checked out git branch on local machine) and does not exist on Pantheon. I have no idea why it would use the git branch on my local machine when I requested that it pull the 'dev' environment.

This could be because my site is using a pull request workflow as described here: 
https://pantheon.io/docs/guides/github-pull-requests/

**Comment by pirog** [comment]
Pushing up a hotfix release for this!
