### ISSUE TITLE
How to target lando app with lando drush/terminus?

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/lando#332]
Feature/Enhancement Request
===========================

Documentation request:
I want to be able to run terminus and drush commands like `drush uli 1` and `drush updatedb` targeting my lando app.

Please provide some detail on how lando can help solve this problem

I am on Windows 10 Pro with landov3-beta13. I created a lando app with the pantheon recipe (drupal 8). 

`lando drush uli admin' gives me:
`We could not find an applicable site for that command.'

**EDIT**
Turns out this was caused by trying to run the drush command from the root of the repo instead of the webroot.  D'oh!

However, I am still having trouble with terminus, as follows:

`lando terminus drush updatedb`

`[error]  The environment argument must be given as <site_name>.<environment>`

What should I set for the <environment> to target the lando app?  In `lando.yml`, I have it set to `dev`, but this is the `dev` environment on the pantheon servers, correct?

**Comment by pirog** [comment]
@ptmkenny you should check out the terminus docs. You need to specify a site/env in the actual command. 

This issue queue is for problems with lando not for support on how to use terminus.
