### ISSUE TITLE
In recipes we have the ability to call stable backdrush, I'd like to be able to put any tag there.

### ISSUE THREAD

**Issue by serundeputy** [kalabox/lando#82]
In recipes in the docs: https://docs.lndo.io/recipes/backdrop.html

```
  # If ommitted this will use the stable backdrush
  backdrush: stable
```
It would be nice to be able to put any tag there or a commit hash to get specific versions of the tools.

**Comment by pirog** [comment]
@serundeputy i think this is now true, can you investigate and either close or comment this out?

**Comment by serundeputy** [comment]
this works; added 

```yml
backdrush: 2d08189446a1de5a62da8d92bb55908b89bf0e5f
```

and received expected functionality above and beyond the `0.0.5` tag! closing.
