### ISSUE TITLE
Mobile Testing, IE Accessing Local Lando URLs w/Devices on the Same Network

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/lando#84]
Feature/Enhancement Request
===========================

As a Lando user who is developing for desktop and mobile devices, I want to be able to access my Lando URLs from mobile phones on my same network so I can speed my development and QA process.

This user story has come up several times on the Kalabox support channel.

**Please provide some detail on how lando can help solve this problem**

There are different apps that can solve this problem (see [this article](http://www.maratz.com/blog/archives/2014/05/06/a-guide-to-accessing-local-websites-from-other-computers-and-mobile-devices/)), wondering if we can package a built-in tool with Lando, or if we just need to have docs around covering this use case.

**Comment by pirog** [comment]
@reynoldsalec im thinking of maybe dishing out anonymous *public* urls on demand that would cover both this use case and the general "how can i show my site to people" use case
https://github.com/localtunnel/localtunnel

**Comment by kristjankoppel** [comment]
Localtunnel or ngrok would be awesome

**Comment by pirog** [comment]
`lando share` will be in the `beta.2` release.
